apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegrambot
  labels:
    app: telegrambot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: telegrambot
  template:
    metadata:
      labels:
        app: telegrambot
    spec:
      containers:
      - name: telegrambot
        image: nicopaez/telegrambot:0.0.7
        ports:
        - containerPort: 4567
        envFrom:
          - configMapRef:
              name: telegrambot-config-env